env:
  - GO111MODULE=on
  - CGO_ENABLED=0

builds:
  - mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - freebsd
      - openbsd
      - linux
      - solaris
    ignore:
      - goarch: "386"
        goos: darwin
      - goarch: "arm"
        goos: openbsd
      - goarch: "arm64"
        goos: openbsd
      - goarch: "arm64"
        goos: freebsd

archives:
  - format: zip
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: false
    files:
      - none*

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

changelog:
  skip: true
