name: homebrew

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

jobs:
  bump-forumla:
    runs-on: ubuntu-latest
    steps:
      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
          tap: leb4r/homebrew-tap
          formula: semtag
          tag: ${{ github.ref }}
          revision: ${{ github.sha }}
          force: true
