name: release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  release:
    name: release (static binaries)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Read go version
        id: go-version
        run: |
          content=`cat ./.go-version`
          echo "::set-output name=content::$content"

      - name: Set up go
        uses: actions/setup-go@v2
        with:
          # TODO: Replace with go-version-from-file when it is supported
          # https://github.com/actions/setup-go/pull/62
          go-version: ${{ steps.go-version.outputs.content }}

      - name: Release static binaries
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
          tap: leb4r/homebrew-tap
          formula: semtag
          tag: ${{ github.ref }}
          revision: ${{ github.sha }}
  # TODO: release container from GitHub Actions
  # container:
  #   name: release (container)
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1
  #     - name: Read go version
  #       id: go-version
  #       run: |
  #         content=`cat ./.go-version`
  #         echo "::set-output name=content::$content"
  #     - name: Read current tag
  #       id: current-tag
  #       run: echo "::set-output name=tag::${GITHUB_REF#refs/*/}"
  #     - name: Login to GitHub Packages
  #       uses: docker/login-action@v1
  #       with:
  #         registry: docker.pkg.github.com
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
  #     - name: Build and push container
  #       id: docker-build
  #       uses: docker/build-push-action@v2
  #       with:
  #         push: true
  #         build-args: |
  #           GOVERSION=${{ steps.go-version.outputs.content }}
  #         tags: |
  #           docker.pkg.github.com/leb4r/semtag/semtag:${{ steps.current-tag.outputs.tag }}
  #     - name: Image digest
  #       run: echo ${{ steps.docker-build.outputs.digest }}
