name: release-drafter

on:
  push:
    branches:
      - main
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Draft next release
        uses: release-drafter/release-drafter@v5
        with:
          publish: ${{ contains(github.ref, "ref/tags") }}
          config-name: release-drafter.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
